server:
  port: 9031
logging:
  file: /LOG/logs/framework/upload/${spring.application.name}.log
  level: debug
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.31.178.149:8001/eureka/
spring:
#  zipkin:
#    base-url: http://localhost:8003/
  output:
    ansi:
      enabled: always
  devtools:
    restart:
      enabled: false
  redis:
    database: 2
    host: 172.31.178.148
    port: 16379
    pool:
      max-active: 8
      max-wait: -1
      min-idle: 0
      max-idle: 8
    password: p2p2018
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

upload:
  rootPath: /MyUpload
  ##rootPath: /home/alan/Pictures/temp
  maxFileSize: 10MB
  maxRequestSize: 20MB

i18n:
  open: true